const {ok, xong} = require("./kiemtra"), {moTrang, loiJS} = require("./trang");
(async () => {
  const {w, $, E, sleep, key, until, errs, puts, blobs, docBlob} = moTrang({olPref: {s2tc: {on: true, op: 0.9}, lulc_ctx: {on: true, op: 0.5}, pc1: {on: true, op: 0.9}}});
  await until(() => E("MAN") && Object.keys(E("ST.diem")).length === 4, 8000, "manifest + E0");
  ok(E("MAN.layers.length") >= 5 && $("ols").querySelectorAll(".ol > label > input[type=checkbox]").length === E("MAN.layers.length") + 1 + (E("MAN.dem") ? 1 : 0), "các lớp đối chiếu + lớp S2 10 băng (+ DEM)");
  ok([...$("selStrip").options].some(o => o.value === "pc1"), "dải ảnh chọn được lớp xám");
  ok($("cls").querySelectorAll("button").length === 17 && $("selRel").options.length > 100, "17 nút lớp, bản Wayback");
  key("n"); await sleep(50); ok(E("ST.cur") === "E0000", "n chọn điểm đầu");
  E("setYear(2023)"); key("q"); await sleep(30);
  ok(E("ST.nam") === 2024 && E("ST.diem.E0000.nhan[2023]") === "X1", "q gán X1 rồi sang năm sau");
  key("c"); await sleep(30); ok(E("ST.diem.E0000.nhan[2024]") === "X1" && E("ST.nam") === 2025, "c chép năm trước");
  key("4"); key("!", {shiftKey: true, code: "Digit3"}); await sleep(30);
  ok(E("ST.diem.E0000.nhan[2025]") === "T1" && E("ST.diem.E0000.tin[2025]") === 3, "4 = T1, Shift+3 tin cậy cao");
  E("select('E0001', true)");
  await until(() => puts.some(p => p.w === 256 && p.op > 1000), 8000, "ô COG");
  ok(puts.some(p => p.w === 256 && p.op > 1000), "vẽ ô COG lên bản đồ");
  await until(() => puts.filter(p => p.w === 97 && p.op > 5000).length >= 2, 8000, "dải ảnh");
  await until(() => /polyline/.test($("curve").innerHTML), 5000, "đường mùa vụ");
  ok(/tính sẵn, k = 3 PC/.test($("curve").innerHTML), "đường mùa vụ tính sẵn, k = 3");
  const nOn = () => E("Object.values(OVL).filter(o => o.layer).length");
  const a = nOn(); key("b"); const b = nOn(); key("b"); const c = nOn();
  ok(a === 3 && b === 0 && c === 3, `b nháy lớp đối chiếu: ${a} -> ${b} -> ${c}`);
  key("m"); E("map.fire('click', {latlng: L.latLng(20.86, 106.68)})"); key("m");
  const tid = E("ST.cur"); ok(/^T/.test(tid) && E(`ST.diem['${tid}'].bo`) === "tay", "chế độ m: thêm điểm tay");
  // nhấp lên bảng lớp đối chiếu (nằm trên bản đồ) khi đang ở chế độ thêm điểm: không được thêm điểm
  const n0 = E("Object.keys(ST.diem).length"); key("m");
  $("ols").querySelector("input[type=checkbox]").click(); $("selBase").dispatchEvent(new w.MouseEvent("mousedown", {bubbles: true}));
  $("panel").dispatchEvent(new w.MouseEvent("click", {bubbles: true})); await sleep(30); key("m");
  ok(E("Object.keys(ST.diem).length") === n0 && E("ST.cur") === tid, "nhấp trên bảng lớp đối chiếu không lọt xuống bản đồ");
  key("a"); await sleep(20);
  blobs.length = 0; $("eLong").click(); $("eWide").click(); $("eJson").click(); $("eGeo").click();
  const [lg, wd, js, gj] = await Promise.all(blobs.map(docBlob));
  const L = lg.replace(/^﻿/, "").split("\r\n");
  ok(L[0].startsWith("id,bo_diem,lon,lat,x_utm,y_utm,tang,nam,ma_lop,id_lop,nhom,lop3") && L.length === 5, `CSV dài: ${L.length - 1} dòng`);
  ok(L.some(r => /^E0000,E0,.*,2023,X1,31,X,3,/.test(r)), "CSV dài: mã lớp, id, nhóm, lop3");
  ok(E("CORE.parseCSV")(wd).length === 5 && JSON.parse(gj).features.length === 5, "CSV rộng và GeoJSON: 5 điểm");
  const J = JSON.parse(js); ok(J.loai === "laymau_hp" && Object.keys(J.st.diem).length === 5 && J.st.vung, "tệp tiến độ JSON");
  await sleep(400); ok(JSON.parse(w.localStorage.getItem("laymau_hp_state_v1")).diem.E0000.nhan[2023] === "X1", "tự lưu vào trình duyệt");
  E(`CORE.setLabel(ST.diem.E0000, 2023, "X2", 1)`); E(`CORE.merge(ST.diem, ${JSON.stringify(J.st.diem)})`);
  ok(E("ST.diem.E0000.nhan[2023]") === "X1", "gộp tiến độ: nhãn mới hơn thắng");
  E("select('E0000', false)"); E("setYear(2025)"); key("Backspace"); ok(E("ST.diem.E0000.nhan[2025]") === undefined, "Backspace xoá nhãn năm");
  key("h"); ok($("dlgHelp").open && /chuột phải/.test($("dlgHelp").textContent), "trợ giúp có hướng dẫn chọn vùng");
  ok(!errs.length, loiJS(errs)); xong();
})().catch(e => { console.error("LỖI", e); process.exit(2); });
