const {ok, xong} = require("./kiemtra"), {moTrang, loiJS} = require("./trang");
const RV = require("/tmp/fx/ref_vung.json");
(async () => {
  const {w, $, E, sleep, key, until, errs, blobs, docBlob} = moTrang({geoman: true});
  const click = (lon, lat, shift) => E(`map.fire("click", {latlng: L.latLng(${lat}, ${lon}), originalEvent: {shiftKey: ${!!shift}}})`);
  await until(() => E("MAN") && E("MAN.layers.length") >= 5, 8000, "manifest");
  ok(E("VG.coPM") === true && E("L.PM.optIn") === true && E("!!map.pm"), "Leaflet-Geoman nạp, opt-in, bản đồ có map.pm");
  E("setYear(2025)"); key("o"); await sleep(50);
  ok(!$("vung").hidden && E("vgDT().join()") === "g7,g7b", "phím o mở bảng; mặc định so bằng g7, g7b");
  await until(() => E("VG.xa && VG.xa.length") === 2, 5000, "ranh giới xã");
  click(RV.lang[0][0], RV.lang[0][1]);
  await until(() => E("VG.res && VG.res.st"), 8000, "vùng liền");
  let st = E("VG.res.st");
  ok(st.n_manh === 1 && Math.abs(st.dien_tich_ha - RV.ha_lang) / RV.ha_lang < 0.15, `vùng liền: ${st.dien_tich_ha.toFixed(2)} ha, 1 mảng`);
  ok(/Theo xã/.test($("vgTK").innerHTML) && /xây dựng|thực vật/.test($("vgTK").innerHTML), "thống kê theo xã và thành phần lớp");
  $("vgPV").value = "bk"; $("vgBK").value = "20"; $("vgPV").onchange();
  await until(() => E("VG.res && VG.res.prm.pv") === "bk", 8000, "bán kính");
  st = E("VG.res.st"); ok(st.n_manh >= 4 && E("VG.data.g.res") > 10, `bán kính 20 km: ${st.n_manh} mảng ở ${E("VG.data.g.res")} m`);
  $("vgPV").value = "xa"; $("vgPV").onchange();
  await until(() => E("VG.res && VG.res.prm.pv") === "xa", 8000, "trong xã");
  st = E("VG.res.st"); ok(st.n_manh === 8 && Object.keys(st.theo_xa).filter(k => +k > 0).length === 1, `trong xã: ${st.n_manh} mảng (2 làng + 6 dải), 1 xã`);
  $("vgTau").value = "0.004"; $("vgTau").oninput(); await sleep(80); const it = E("VG.res.st.n_px");
  $("vgTau").value = "0.08"; $("vgTau").oninput(); await sleep(80);
  ok(it < E("VG.res.st.n_px") / 3, "ngưỡng chặt chọn ít hơn hẳn");
  key("4"); await sleep(50);
  ok(E("VG.sua.getLayers().length") >= 8 && E("VG.pmOn") && E("VG.sua.getLayers()[0].options.pmIgnore") === false, "phím 4: đa giác sửa được bằng Geoman");
  E("VG.sua.getLayers()[0].pm.enable()"); ok(E("VG.sua.getLayers()[0].pm.enabled()"), "bật sửa đỉnh"); E("VG.sua.getLayers()[0].pm.disable()");
  const n0 = E("VG.sua.getLayers().length");
  E("(() => { const l = VG.sua.getLayers()[0]; map.fire('pm:remove', {layer: l}); map.removeLayer(l); })()");
  $("vgCapNhat").click();
  await until(() => E("VG.res.st_sua") && E("VG.res.st_sua.n_manh") === n0 - 1, 8000, "thống kê theo ranh giới");
  ok(/mặt cầu/.test($("vgTK").innerHTML), `sau khi xoá 1 đa giác: ${E("VG.res.st_sua.n_manh")} mảng, có diện tích mặt cầu`);
  $("vgLop").value = "X2"; $("vgTen").value = "làng thử"; await E("vgLuu()");
  ok(E("Object.keys(ST.vung).length") === 1 && E("Object.values(ST.vung)[0].da_sua"), "lưu vùng, đánh dấu đã sửa");
  blobs.length = 0; $("eVung").click(); $("eVungCSV").click();
  const [gj, csv] = await Promise.all(blobs.map(docBlob)); const fc = JSON.parse(gj);
  ok(fc.features[0].properties.loai === "vung_mau" && fc.features[0].geometry.type === "MultiPolygon" && /dien_tich_ha/.test(csv), "xuất GeoJSON và CSV vùng");
  E(`vungNhapGeo(${JSON.stringify(fc)}, "x.geojson")`); ok(E("Object.keys(ST.vung).length") === 1, "nhập lại không nhân đôi");
  key("1"); $("vgPV").value = "bk"; $("vgBK").value = "20"; $("vgPV").onchange();
  await until(() => E("VG.res && VG.res.prm.pv") === "bk" && E("VG.obj.kieu") === "mang", 8000, "lại bán kính");
  await E("vgNam9()");
  const bang = E("VG.namTK.bang");
  ok(bang.length === 2 && bang[0].manh < bang[1].manh, `so sánh các năm: ${bang.map(r => r.nam + ": " + r.manh + " mảng").join("; ")} (2023 thiếu một làng)`);
  $("vgNDiem").value = "12"; $("vgRai").click(); await sleep(30);
  ok(E("Object.values(ST.diem).filter(p => p.bo === 'vung' && p.nhan[2025] === 'X2').length") === 12, "rải 12 điểm có nhãn X2");
  key("1"); click(RV.lang[1][0], RV.lang[1][1], true); await sleep(400);
  ok(E("VG.neg.length") === 1, "Shift+nhấp: điểm mẫu loại trừ");
  key("o"); ok($("vung").hidden && !E("VG.pmOn"), "phím o đóng bảng");
  ok(!errs.length, loiJS(errs)); xong();
})().catch(e => { console.error("LỖI", e); process.exit(2); });
